### PR TITLE
Add more information in README.md for "Getting started"

### PR DESCRIPTION
**Pull request by libook**
Wish help

### CODE REVIEW

**Comment by TatriX** [comment]
Hi! Thanks for the PR!
Should we maybe instead suggest to `export DATABASE_URL=...` so user don't have to put it in every command? Or point to `dotenv` and `diesel` guide in general.

**Comment by libook** [comment]
@TatriX 
I have thought about it. It is just a "getting started", so I wish it to be simple as possible. To help people quickly make it run. 👌

The usage of environment variables can not be explained with couple of words. 🤔  If I tell you that you should use an environment variable. Then I can advice you to use an 'export' command to keep the variable in current shell session. Then I need to tell you that you can put the 'export' command into your .bashrc, .zshrc... to make it run every time you logedin. 💫 Well, IDE and container technology users may used to deal with environment variables in different ways. If they need a different way to use environment variables, they probbly already know all about it.

Or we can just put a manual link of environment variables on it. 😂

**Comment by TatriX** [comment]
Maybe something like this could work?
```sh
# First let's setup database url
export DATABASE_URL=...
# Take a look at `dotenv` project
# if you want to have env variables on per directory basis

# diesel will consult DATABASE_URL
diesel ...
# Of course you can provide them manually:
diesel --database-url...
```

**Comment by libook** [comment]
@TatriX 
Yes, `DATABASE_URL` works in theory.

`dotenv` provided a new way to manage environment variables. It's good.

My view is to let any newbie can successfuly run this project in few command, one minute. So I'm trying not to include any unnessesery knowledge; to avoid generating cognitive costs.

So there can be 2 chapters: "quick start" and "advices". We can put advanced needs into "advices" chapter.

**Comment by TatriX** [comment]
> My view is to let any newbie can successfuly run this project in few command

Well, then perhaps docker image could be a better solution.

My thinking here is that this project's goak isn't to teach how to use shell or write rust, but about giving a useful example of real world code base and workflow. And from my point of view having static configuration in all you shell commands is quite uncomfortable.

So at least I would go for something like this:
```sh
export DATABASE_URL=...
diesel migration run --database-url $DATABASE_URL
```

**Comment by libook** [comment]
@TatriX 

> My thinking here is that this project's goak isn't to teach how to use shell or write rust, but about giving a useful example of real world code base and workflow. 

I completely agree with you.

Your original version is very comfortable. But it doesn't work on my OS. Then I realized that I have to tell these commands more about database. Especialy; `psql` need an exist DBA account; and the `DATABASE_URL` variable is required (hard code in config.rs). This is why I send this PR.

I just point the issue out. Please feel free to improve it in any way you like.

**Comment by TatriX** [comment]
Ok, I think we should put these into a separate file, say, `GUIDE.md` and make a reference in the readme. In this way we can cover both use cases: if you already know how to use psql and have your preferences and when you are just starting out.

**Comment by libook** [comment]
Will you do it? What can I do for you?

**Comment by TatriX** [comment]
If you can do that, it would be great! I'm a bit overwhelmed with other tasks right now, sorry :)

**Pull request closed without merging**
