### PR TITLE
chore(ci): Add TravisCI

### PR DESCRIPTION
**Pull request by anishkny**
Hi @TatriX,

I tried to enable TravisCI but the build keeps [failing](https://travis-ci.org/anishkny/realworld-rust-rocket/builds), could you help out?

### CODE REVIEW

**Comment by TatriX** [comment]
Hi!
```
+  - mysql
```
The project uses `postgres`. probably this is the problem.

**Comment by anishkny** [comment]
@TatriX, 

Yeah switching to Postgres worked but now it fails with:

```
test a_auth::register ... POST /api/users application/json:
    => Matched: POST /api/users application/json
thread '<unnamed>' panicked at 'count username: DatabaseError(__Unknown, "relation \"users\" does not exist")', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
FAILED
```

See: https://travis-ci.org/anishkny/realworld-rust-rocket/builds/355064563#L532

Do I need to create tables in `init.sql`?

**Comment by TatriX** [comment]
You need to run migrations with [diesel](http://diesel.rs/guides/getting-started/).
Setup a `diesel` cli and run the migrations:
```sh
cargo install diesel_cli
diesel migration run
```

**Comment by anishkny** [comment]
Thanks seems to be working now. PTAL.

**Comment by TatriX** [comment]
It looks awesome, thanks!
The only question I have is why do you need to uninstall diesel_cli before installing it?

**Comment by TatriX** [comment]
Also there is a `/tests/test.sh` which run a `realworld` test collection with `newman`. I think it can be good for CI too.

**Comment by anishkny** [comment]
I am new to rust/cargo. It was failing if diesel_cli was already installed. I think I have a solution in #2

**Comment by TatriX** [comment]
Cool, thank you again!

**Pull request merged**
