### PR TITLE
Feat author type from user to profile

### PR DESCRIPTION
**Pull request by luchoman08**

### CODE REVIEW

**Comment by luchoman08** [comment]
The optional authorization class was a risky proposition due to my limited knowledge on the subject, so I would appreciate any suggestions.

First of all the reason why I think it is necessary is the route `GET /articles/{slug/comments`, since the comments need a profile in the author field, it is necessary to return a valid `following` val, for which it is necessary have knowledge of the id of the logged in user, however this does not go in the payload of the frontend information, it is deducted from the jwt token, adding `Auth` to `GET comments` this is solved but that makes unauthenticated users can not access the comments, so I proposed an `AuthOptional` class and the best way I saw it was creating a class with the same characteristics of `Auth` but with these type `Option`. If exists a logged user `AuthOptional` properties take `Some` in each one and take `None` otherwise.

**Comment by TatriX** [comment]
You can do something like this:
```rust
 pub fn get_comments(slug: String, conn: db::Conn, auth: Option<Auth>) -> Json<JsonValue> {
```

Also could you please include a link to a documentation of the protocol describing the change. It would be useful to put it in the commit message.

**Comment by luchoman08** [comment]
Function [`get_comments`](https://github.com/TatriX/realworld-rust-rocket/blob/17ea029102161e2b0c25ca1688de5e0855d9942d/src/routes/articles.rs) has been modified as suggested, previously wrong code for optional auth was removed

**Comment by luchoman08** [comment]
This pull request was replaced by [this pull request](https://github.com/TatriX/realworld-rust-rocket/pull/12), pull request #12 contains all the changes of this,  with the function get_comments as was suggested and other changes described by the pull.

**Pull request closed without merging**
