### PR TITLE
Fix Frank JWT decode

### PR DESCRIPTION
**Pull request by ghost**
The function decode has changed to Frank_jwt and needs 4 parameters

### CODE REVIEW

**Comment by TatriX** [comment]
Thanks for the PR.
It's a bit strange though that on travis it tried to compile `frank_jwt v3.1.2` when it has an explicit version of `3.1.1` in `Cargo.toml`. It would be nice to find out how this happened in the first place to prevent this from happening in the future.

**Comment by TatriX** [comment]
Ok, my bad:
```
... 0.1.0” does not mean exactly 0.1.0, it’s a synonym for “^0.1.0”. You want “=0.1.0” to get exact.
```

**Comment by ghost** [comment]
Thats true
I have the same problem on my Localen computer.
the version from Cargo.toml is ignored.

> The string "3.1.1" is a semver version requirement. Since this string does not have any operators in it, it is interpreted the same way as if we had specified "^3.1.1", which is called a caret requirement.

>

**Comment by ghost** [comment]
> Ok, my bad:
> 
> ```
> ... 0.1.0” does not mean exactly 0.1.0, it’s a synonym for “^0.1.0”. You want “=0.1.0” to get exact.
> ```

Found the same :)

**Pull request merged**
